name: OpenIM Create Tag

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  create-tag:
    if: startsWith(github.event.comment.body, '/create tag')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        user: kubbot # 将 "username" 替换为您想要使用的 GitHub 用户名

    - name: Set up Git user
      run: |
        git config user.name "kubbot" # 将 "Your Name" 替换为您想要使用的名字
        git config user.email "3293172751ysy@gmail.com" # 将 "you@example.com" 替换为您想要使用的邮箱地址

    - name: Create Tag
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        TAG=$(echo $COMMENT_BODY | awk '{print $3}')
        COMMENT=$(echo $COMMENT_BODY | awk '{$1=$2=$3=""; print $0}')
        COMMENT=$(echo $COMMENT | sed 's/^ *//;s/ *$//')  # Remove leading and trailing whitespaces
        
        if [[ -z "$TAG" || -z "$COMMENT" ]]; then
          echo "Error: Tag name or comment is empty"
          exit 1
        fi
        
        echo "Creating tag $TAG with comment '$COMMENT'"
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git tag -a $TAG -m "$COMMENT"
        git push origin $TAG

      env:
        GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
